backend/models/ContactForm.php
<?php

/**
 * ContactForm class.
 * ContactForm is the data structure for keeping
 * contact form data. It is used by the 'contact' action of 'SiteController'.
 */
class ContactForm extends CFormModel
{
	public $name;
	public $email;
	public $subject;
	public $body;
	public $verifyCode;

	/**
	 * Declares the validation rules.
	 */
	public function rules()
	{
		return array(
			// name, email, subject and body are required
			array('name, email, subject, body', 'required'),
			// email has to be a valid email address
			array('email', 'email'),
			// verifyCode needs to be entered correctly
			array('verifyCode', 'captcha', 'allowEmpty'=>!CCaptcha::checkRequirements()),
		);
	}

	/**
	 * Declares customized attribute labels.
	 * If not declared here, an attribute would have a label that is
	 * the same as its name with the first letter in upper case.
	 */
	public function attributeLabels()
	{
		return array(
			'verifyCode'=>'Verification Code',
		);
	}
}

frontend/models/Contact.php
<?php

/**
 * Class Contact
 *
 * Class for work with user contacts
 *
 * @property string $id
 * @property string $owner_id
 * @property string $user_id
 * @property string $contact_email
 * @property string $title
 * @property string $group_id
 * @property integer $date_created
 * @property integer $date_updated
 *
 * @author andymitrich <andymitrich@gmail.com>
 * @version 1.0
 */
class Contact extends ActiveRecord
{
    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Contact the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'contact';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('owner_id, user_id, group_id', 'length', 'max' => 11),
            array('email', 'email'),
            array('title', 'length', 'max' => 255),
            array('id, owner_id, user_id, title, group_id', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'owner_id' => 'Owner',
            'user_id' => 'User',
            'title' => 'Title',
            'group_id' => 'Group',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('owner_id', $this->owner_id, true);
        $criteria->compare('user_id', $this->user_id, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('group_id', $this->group_id, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function beforeSave() {

        if ($this->isNewRecord) $this->date_created = time();

        $this->date_updated = time();

        return parent::beforeSave();
    }
}

frontend/controllers/ContactController.php
<?php

/**
 * Class ContactController
 *
 * Controller for processing contacts
 *
 * @author andymitrich <andymitrich@gmail.com>
 * @version 1.0
 */
class ContactController extends FrontEndController
{
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array();
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render(
            'view',
            array(
                'model' => $this->loadModel($id),
            )
        );
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @throws Exception
     */
    public function actionCreate()
    {
        if (app()->hasComponent('user') && user()->id) {
            $model = new Contact;
            $contactData = request()->getPost('Contact');

            if (sizeof($contactData)) {

                $model->attributes = $contactData;
                $model->owner_id = user()->id;

                if ($model->save()) {
                    $this->redirect(array('index'));
                }
            }

            $this->render(
                'create',
                array(
                    'model' => $model,
                )
            );
        } else {
            throw new Exception(404, 'The requested page does not exist.');
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        if (app()->hasComponent('user') && user()->id) {
        $model = $this->loadModel($id);

        if (isset($_POST['Contact'])) {
            $model->attributes = $_POST['Contact'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render(
            'update',
            array(
                'model' => $model,
            )
        );
        }else {
            throw new Exception(404, 'The requested page does not exist.');
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $contactList = array();

        // Check user authorization
        if (app()->hasComponent('user') && user()->id) {

            $ownerId = user()->id;

            $rows = Contact::model()->findAllByAttributes(array('owner_id'=>$ownerId));
            $model = new Contact();

            $this->render(
                'index',
                array(
                    'list' => $rows,
                    'model' => $model
                )
            );
        } else {
            $this->redirect(array('site/login'));
        }


    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Contact the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Contact::model()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Contact $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'contact-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionComplete()
    {

        $query = request()->getQuery('q', '');
        $result = array();

        if (!empty($query)) {

            $command = command()
                ->select('name, surname, email')
                ->from('user');

            $where = "
                name LIKE '%$query%' OR
                surname LIKE '%$query%' OR
                email LIKE '%$query%'
            ";
            $command->setWhere($where);

            $rows = $command->queryAll();

            if (sizeof($rows)) {
                foreach ($rows as $row) {

                    $current = array();
                    $current['value'] = $row['email'];
                    $current['full'] = "{$row['name']} {$row['surname']} <{$row['email']}>";
                    $result[] = $current;;
                }
            }
        }

        echo CJSON::encode($result);;
        Yii::app()->end();
    }
}

frontend/views/contact/_contact.php
<div class="cAvatar">
    <a href="#"><img src="img/elem/no-avatar.png" alt=""></a>
</div>
<?php if ($model->group_id) : ?>
<span class="cGroup">
    <a href="#"><?php echo Group::getGroupTitle($model->group_id); ?></a>
</span>
<?php else : ?>
<span class="cGroup">
    <a href="#" class="no-group">Без группы</a>
</span>
<?php endif; ?>
<span class="cName"><a href="#"><?php echo CHtml::encode($model->title); ?></a></span>
<!--<span class="cNumber">Записей в совместном доступе: 18</span>-->
<div class="cButton">
    <div class="buttonHolder">
        <a href="<?php echo Yii::app()->urlManager->createUrl('contact/update', array('id'=>$model->id)); ?>">Редактировать</a>
    </div>
</div>

frontend/views/contact/_create_form.php
<?php
/* @var $this ContactController */
/* @var $model Contact */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php $form = $this->beginWidget(
        'ActiveForm',
        array(
            'id' => 'contact-create-form',
            'enableAjaxValidation' => false,
        )
    ); ?>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo CHtml::textField('person', 'Начните вводить фамилию, имя, e-mail контакта', array('size' => 60, 'maxlength' => 255, 'class' => 'autocomplete typeahead')); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'title'); ?>
        <?php echo $form->textField($model, 'title', array('size' => 60, 'maxlength' => 255, 'value' => 'Как отображать этот контакт', 'class' => 'autoclear')); ?>
        <?php echo $form->error($model, 'title'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Добавить контакт'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

frontend/views/contact/_form.php
<?php
/* @var $this ContactController */
/* @var $model Contact */
/* @var $form CActiveForm */
?>
<style>
    .contact-type
    {

    }
    .contact-description
    {
        font-size: 10px;
    }
</style>
<script type="text/javascript">
    $(function() {
        $('#Contact_email').typeahead({
            name: 'person',
            remote: 'index.php?r=contact/complete&q=%QUERY',
            limit: 20,
            template: [
                '<p class="contact-name">{{value}}</p>',
                '<p class="contact-description">{{full}}</p>'
            ].join(''),
            engine: Hogan
        });
    })

</script>

<div class="form" style="padding-left: 30px;">

    <?php $form = $this->beginWidget(
        'ActiveForm',
        array(
            'id' => 'contact-create-form',
            'enableAjaxValidation' => false,
            'action'=>Yii::app()->urlManager->createUrl('contact/create')
        )
    ); ?>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->textField($model, 'email', array('value'=> 'Начните вводить фамилию, имя, e-mail контакта','size' => 60, 'maxlength' => 255, 'class' => 'styled-input typeahead')); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'title'); ?>
        <?php echo $form->textField($model, 'title', array('size' => 60, 'maxlength' => 255, 'value' => 'Как отображать этот контакт', 'class' => 'styled-input')); ?>
        <?php echo $form->error($model, 'title'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Добавить контакт'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

frontend/views/contact/_search.php
<?php
/* @var $this ContactController */
/* @var $model Contact */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'owner'); ?>
		<?php echo $form->textField($model,'owner',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user'); ?>
		<?php echo $form->textField($model,'user',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'group'); ?>
		<?php echo $form->textField($model,'group',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

frontend/views/contact/_update_form.php
<?php
/* @var $this ContactController */
/* @var $model Contact */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'owner'); ?>
		<?php echo $form->textField($model,'owner',array('size'=>11,'maxlength'=>11)); ?>
		<?php echo $form->error($model,'owner'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'user'); ?>
		<?php echo $form->textField($model,'user',array('size'=>11,'maxlength'=>11)); ?>
		<?php echo $form->error($model,'user'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'group'); ?>
		<?php echo $form->textField($model,'group',array('size'=>11,'maxlength'=>11)); ?>
		<?php echo $form->error($model,'group'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

frontend/views/contact/_view.php
<?php
/* @var $this ContactController */
/* @var $data Contact */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('owner')); ?>:</b>
	<?php echo CHtml::encode($data->owner); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user')); ?>:</b>
	<?php echo CHtml::encode($data->user); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('group')); ?>:</b>
	<?php echo CHtml::encode($data->group); ?>
	<br />


</div>

frontend/views/contact/admin.php
<?php
/* @var $this ContactController */
/* @var $model Contact */

$this->breadcrumbs=array(
	'Contacts'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Contact', 'url'=>array('index')),
	array('label'=>'Create Contact', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#contact-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Contacts</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'contact-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'owner',
		'user',
		'title',
		'group',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

frontend/views/contact/create.php
<div id="myModal" style="width: 610px" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
        <?php $this->renderPartial('_form', array('model' => $model)); ?>
    </div>
</div>

frontend/views/contact/index.php
<div class="row-fluid wrapperGroupHolder">
    <div class="span12 headerGroup">
        <div class="groupLeft">
            <h1>Контакты</h1>
        </div>
        <div class="groupRight">
            <div class="buttonHolder">
                <?php echo CHtml::link('Добавить контакт', '#myModal', array('data-toggle'=>"modal",'class'=>"blueButton")); ?>
            </div>
            <div class="folderSearchHolder contactsSearch">
                <input class="styled-input" type="text" name="search" value="Поиск среди контактов"/>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid wrapperGroupContentHolder normal">
<div class="span12 simpleGroupHolder">
<div class="socialButtonsHolder clearfix">
    <span>Вы можете импортировать контакты из социальных сетей и почты</span>
    <ul class="socialButtonList">
        <li><a href="#"><img src="img/icons/icon-mail.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/mail-co.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/ok-ico.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/icon-twitter.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/vk-ico.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/yandex-ico.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/facebook-ico.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/google-ico.png" alt=""></a></li>
        <li><a href="#"><img src="img/icons/link-ico.png" alt=""></a></li>
    </ul>
    <a href="#" class="closeButton">Закрыть</a>
</div>
<div class="contactsListHolder clearfix">
    <?php if (sizeof($list)) : ?>
    <ul class="contactsList">
        <?php foreach ($list as $row) : ?>
        <li>
            <?php $this->renderPartial('_contact',array('model'=>$row)); ?>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
</div>
</div>
<?php $this->renderPartial('create',array('model'=>$model)); ?>

frontend/views/contact/update.php
<?php
/* @var $this ContactController */
/* @var $model Contact */

$this->breadcrumbs=array(
	'Contacts'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Contact', 'url'=>array('index')),
	array('label'=>'Create Contact', 'url'=>array('create')),
	array('label'=>'View Contact', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Contact', 'url'=>array('admin')),
);
?>

<h1>Update Contact <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

frontend/views/contact/view.php
<?php
/* @var $this ContactController */
/* @var $model Contact */

$this->breadcrumbs=array(
	'Contacts'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'List Contact', 'url'=>array('index')),
	array('label'=>'Create Contact', 'url'=>array('create')),
	array('label'=>'Update Contact', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Contact', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Contact', 'url'=>array('admin')),
);
?>

<h1>View Contact #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'owner',
		'user',
		'title',
		'group',
	),
)); ?>