frontend/models/Group.php
<?php

/**
 * Class Group
 *
 * Class for work with groups of contacts
 *
 * @property string $id
 * @property string $title
 * @property string $owner_id
 * @property string $contact_count
 *
 * @author andymitrich <andymitrich@gmail.com>
 * @version 1.0
 */
class Group extends ActiveRecord
{
    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Group the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'group';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('title', 'length', 'max' => 255),
            array('owner_id', 'length', 'max' => 11),
            array('contact_count', 'length', 'max' => 5),
            array('id, title, owner_id, contact_count', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'title' => 'Title',
            'owner_id' => 'Owner',
            'contact_count' => 'Contact Count',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('owner_id', $this->owner_id, true);
        $criteria->compare('contact_count', $this->contact_count, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public static function getGroupTitle($id) {

        /**
         * @var $model Group
         */
        $model = self::model()->findByPk($id);

        return $model->title;
    }
}

frontend/controllers/GroupController.php
<?php

/**
 * Class GroupController
 *
 * Controller for groups
 *
 * @author andymitrich <andymitrich@gmail.com>
 * @version 1.0
 */
class GroupController extends FrontEndController
{
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array();
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        if (app()->hasComponent('user') && user()->id) {

            $model = new Group;
            $groupData = request()->getPost('Group', array());

            if (sizeof($groupData)) {

                $model->attributes = $_POST['Group'];
                $model->owner_id = user()->id;

                if ($model->save()) {

                    $this->redirect(array('index'));
                }
            }

            $this->render(
                'create',
                array(
                    'model' => $model,
                )
            );
        } else {
            throw new Exception(404, 'The requested page does not exist.');
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        if (app()->hasComponent('user') && user()->id) {

            $model = $this->loadModel($id);
            $groupData = request()->getPost('Group', array());

            if (sizeof($groupData)) {

                $model->attributes = $_POST['Group'];

                if ($model->save()) {

                    $this->redirect(array('index'));
                }
            }

            $this->render(
                'update',
                array(
                    'model' => $model,
                )
            );
        } else {
            throw new Exception(404, 'The requested page does not exist.');
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     * @throws Exception
     */
    public function actionDelete($id)
    {
        if (app()->hasComponent('user') && user()->id) {

            $this->loadModel($id)->delete();

            if (request()->getQuery('ajax')) {

                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
            }
        } else {
            throw new Exception(404, 'The requested page does not exist.');
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        if (app()->hasComponent('user') && user()->id) {

            $contact = new Contact();
            $group = new Group();
            $ownerId = user()->id;
            $groups = Group::model()->findAllByAttributes(array('owner_id' => $ownerId));
            $this->render(
                'index',
                array(
                    'contact' => $contact,
                    'group' => $group,
                    'list' => $groups
                )
            );
        } else {
            $this->redirect(array('site/login'));
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Group the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Group::model()->findByPk($id);

        if ($model === null) {

            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Group $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'group-form') {

            echo ActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionLoadContacts()
    {
        if (request()->isAjaxRequest) {
            $group = new Group();
            echo $this->render('_inner_extended_row', array('group'=>$group));
        } else {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
    }
}

frontend/views/group/_contact_form.php
<?php
/* @var $this ContactController */
/* @var $model Contact */
/* @var $form CActiveForm */
?>
<style>
    .contact-type
    {

    }
    .contact-description
    {
        font-size: 10px;
    }
</style>
<script type="text/javascript">
    $(function() {
        $('#Contact_email').typeahead({
            name: 'person',
            remote: 'index.php?r=contact/complete&q=%QUERY',
            limit: 20,
            template: [
                '<p class="contact-name">{{value}}</p>',
                '<p class="contact-description">{{full}}</p>'
            ].join(''),
            engine: Hogan
        });
    })

</script>

<div class="form" style="padding-left: 30px;">

    <?php $form = $this->beginWidget(
        'ActiveForm',
        array(
            'id' => 'contact-create-form',
            'enableAjaxValidation' => false,
            'action'=>Yii::app()->urlManager->createUrl('contact/create')
        )
    ); ?>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->textField($model, 'email', array('value'=> 'Начните вводить фамилию, имя, e-mail контакта','size' => 60, 'maxlength' => 255, 'class' => 'styled-input typeahead')); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'title'); ?>
        <?php echo $form->textField($model, 'title', array('size' => 60, 'maxlength' => 255, 'value' => 'Как отображать этот контакт', 'class' => 'styled-input')); ?>
        <?php echo $form->error($model, 'title'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Добавить контакт'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

frontend/views/group/_form.php
<?php
/* @var $this GroupController */
/* @var $model Group */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'group-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'owner'); ?>
		<?php echo $form->textField($model,'owner',array('size'=>11,'maxlength'=>11)); ?>
		<?php echo $form->error($model,'owner'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'contact_count'); ?>
		<?php echo $form->textField($model,'contact_count',array('size'=>5,'maxlength'=>5)); ?>
		<?php echo $form->error($model,'contact_count'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

frontend/views/group/_group_form.php
<?php
/* @var $this GroupController */
/* @var $model Group */
/* @var $form ActiveForm */
?>

<div class="form" style="padding-left: 30px;">
    <?php $form = $this->beginWidget(
        'ActiveForm',
        array(
            'id' => 'group-form',
            'enableAjaxValidation' => false,
            'action' => ($model->isNewRecord) ? Yii::app()->urlManager->createUrl('group/create') :
                Yii::app()->urlManager->createUrl('group/update')
        )
    ); ?>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'title'); ?>
        <?php echo $form->textField($model, 'title', array('size' => 60, 'maxlength' => 255)); ?>
        <?php echo $form->error($model, 'title'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

frontend/views/group/_inner_extended_row.php
<div class="headrGroup">
    <h1><?php echo $group->title; ?></h1>
    <div class="listDiskSpace-button">
        <a href="#">Удалить</a>
    </div>
    <div class="buttonHolder">
        <a href="#">Редактировать</a>
    </div>
</div>
<ul class="innerListGroup sortable">
    <li>
        <img src="img/elem/drag.png" class="handlerIco" alt="">
        <p><a href="#">Венглинский Дмитрий Сергеевич </a>Записей в совместном доступе: 18</p>
        <div class="listDiskSpace-button">
            <a href="#">Удалить</a>
        </div>
    </li>
    <li>
        <img src="img/elem/drag.png" class="handlerIco" alt="">
        <p><a href="#">Василий Алибабаевич Пупкин </a>Записей в совместном доступе: 1</p>
        <div class="listDiskSpace-button">
            <a href="#">Удалить</a>
        </div>
    </li>
    <li>
        <img src="img/elem/drag.png" class="handlerIco" alt="">
        <p><a href="#">operator8tv@gmail.com </a>Записей в совместном доступе: 42</p>
        <div class="listDiskSpace-button">
            <a href="#">Удалить</a>
        </div>
    </li>
</ul>

frontend/views/group/_inner_short_row.php
<div class="groupListBlock clearfix">
    <div class="logoGroup">
        <div class="headerImgHolderGroup">
            <img src="img/content/groupLogo.png" alt=""/>
            <span>группа</span>
        </div>
        <div class="button-holder">
            <?php echo CHtml::link('Добавить', '#createContact', array('data-toggle'=>"modal",'class'=>'green-button')); ?>
        </div>
    </div>
    <div class="headrGroup">
        <h1><?php echo $group->title; ?></h1>
        <div class="listDiskSpace-button">
            <a href="#">Удалить</a>
        </div>
        <div class="buttonHolder">
            <a href="<?php echo Yii::app()->urlManager->createUrl('group/update', array('id'=>$group->id)); ?>">Редактировать</a>
        </div>
    </div>
    <ul class="innerListGroup sortable">
        <li>
            <img src="img/elem/drag.png" class="handlerIco" alt="">
            <p><a href="#">Венглинский Дмитрий Сергеевич </a>Записей в совместном доступе: 18</p>
            <div class="listDiskSpace-button">
                <a href="#">Удалить</a>
            </div>
        </li>
        <li>
            <img src="img/elem/drag.png" class="handlerIco" alt="">
            <p><a href="#">Василий Алибабаевич Пупкин </a>Записей в совместном доступе: 1</p>
            <div class="listDiskSpace-button">
                <a href="#">Удалить</a>
            </div>
        </li>
        <li>
            <img src="img/elem/drag.png" class="handlerIco" alt="">
            <p><a href="#">operator8tv@gmail.com </a>Записей в совместном доступе: 42</p>
            <div class="listDiskSpace-button">
                <a href="#">Удалить</a>
            </div>
        </li>
        <li>
            <img src="img/elem/drag.png" class="handlerIco" alt="">
            <p><a href="#">Варвара </a>Записей в совместном доступе: 7356</p>
            <div class="listDiskSpace-button">
                <a href="#">Удалить</a>
            </div>
        </li>
        <li>
            <img src="img/elem/drag.png" class="handlerIco" alt="">
            <p><a href="#">mhaff@mail.ru </a>Записей в совместном доступе: 18</p>
            <div class="listDiskSpace-button">
                <a href="#">Удалить</a>
            </div>
        </li>
        <li>
            <img src="img/elem/drag.png" class="handlerIco" alt="">
            <p><a href="#">Венглинский Дмитрий Сергеевич </a>Записей в совместном доступе: 18</p>
            <div class="listDiskSpace-button">
                <a href="#">Удалить</a>
            </div>
        </li>
    </ul>
</div>

frontend/views/group/_search.php
<?php
/* @var $this GroupController */
/* @var $model Group */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'owner'); ?>
		<?php echo $form->textField($model,'owner',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'contact_count'); ?>
		<?php echo $form->textField($model,'contact_count',array('size'=>5,'maxlength'=>5)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

frontend/views/group/_view.php
<?php
/* @var $this GroupController */
/* @var $data Group */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('owner')); ?>:</b>
	<?php echo CHtml::encode($data->owner); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('contact_count')); ?>:</b>
	<?php echo CHtml::encode($data->contact_count); ?>
	<br />


</div>

frontend/views/group/admin.php
<?php
/* @var $this GroupController */
/* @var $model Group */

$this->breadcrumbs=array(
	'Groups'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Group', 'url'=>array('index')),
	array('label'=>'Create Group', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#group-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Groups</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'group-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'title',
		'owner',
		'contact_count',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

frontend/views/group/create.php
<?php $this->beginWidget(
    'zii.widgets.jui.CJuiDialog',
    array(
        'id' => 'group-create',
        'options' => array(
            'title' => 'Добавить группу',
            'autoOpen' => false,
            'modal' => true,
            'resizable' => false,
            'width' => 600
        ),
    )
);

$this->renderPartial('_form', array('model' => $model));

$this->endWidget('zii.widgets.jui.CJuiDialog');

frontend/views/group/createContact.php
<div id="createContact" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
        <?php $this->renderPartial('_contact_form', array('model' => $contact)); ?>
    </div>
</div>

frontend/views/group/createGroup.php
<div id="createGroup" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
        <?php $this->renderPartial('_group_form', array('model' => $group)); ?>
    </div>
</div>);

frontend/views/group/index.php
<?php
clientScript()->registerScript('load_contacts', '
$(function() {

    $(".contact_group").on("click", function() {

        var group = $(this).attr("group_id");

        $.ajax({
            url: "index.php?r=group/loadContacts",
            data: {group: group},
            dataType: "json",
            type: "POST"
        }).done(function(data) {


            $(".folder_entries_content").html(out);

            $(".folder_entries_content").sortable();
        });
    });
})
');
?>
<div class="row-fluid wrapperGroupHolder">
    <div class="span12 headerGroup">
        <div class="groupLeft">
            <h1>Группы</h1>
            <ul class="wrapperGroup">
                <li class="expansionGroup active"><a href="#">Упрощенный вид</a></li>
                <li class="simpleGroup"><a href="#">Расширенный вид</a></li>
            </ul>
        </div>
        <div class="groupRight">
            <div class="buttonHolder">
                <?php echo CHtml::link('Добавить группу', '#createGroup', array('data-toggle'=>"modal",'class'=>"blueButton")); ?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid wrapperGroupContentHolder extended tabs">
    <div class="span3 left-side">
        <?php if (sizeof($list)) : ?>
        <ul class="navGroupList">
            <?php foreach ($list as $key=>$row) : ?>
                <li><a class="contact_group" group_id="<?php echo $row->id; ?>" href="#tab<?php echo $key + 1; ?>"><span class="borderSpan"></span><?php echo $row->title; ?><span class="activeBorder"></span></a></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <div class="addButton">
            <?php echo CHtml::link('Добавить группу', '#createGroup', array('data-toggle'=>"modal")); ?>
        </div>
    </div>
    <div class="span9 main-content">
        <?php if (sizeof($list)) : ?>
            <?php foreach ($list as $key=>$row) : ?>
                <div class="groupListBlock clearfix"  id="tab<?php echo $key + 1; ?>">
                    <?php $this->renderPartial('_inner_extended_row', array('group'=>$row)); ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<div class="row-fluid wrapperGroupContentHolder normal">
    <div class="span12 simpleGroupHolder">
        <?php if (sizeof($list)) : ?>
            <?php foreach ($list as $row) : ?>
                <?php $this->renderPartial('_inner_short_row', array('group'=>$row)); ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<?php $this->renderPartial('createGroup',array('group'=>$group)); ?>
<?php $this->renderPartial('createContact',array('contact'=>$contact)); ?>

frontend/views/group/update.php
<?php
/* @var $this GroupController */
/* @var $model Group */

$this->breadcrumbs=array(
	'Groups'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Group', 'url'=>array('index')),
	array('label'=>'Create Group', 'url'=>array('create')),
	array('label'=>'View Group', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Group', 'url'=>array('admin')),
);
?>

<h1>Update Group <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

frontend/views/group/view.php
<?php
/* @var $this GroupController */
/* @var $model Group */

$this->breadcrumbs=array(
	'Groups'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'List Group', 'url'=>array('index')),
	array('label'=>'Create Group', 'url'=>array('create')),
	array('label'=>'Update Group', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Group', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Group', 'url'=>array('admin')),
);
?>

<h1>View Group #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'title',
		'owner',
		'contact_count',
	),
)); ?>